### ISSUE TITLE
开源协议？

### ISSUE THREAD

**Issue by linlinjava** [qianzhaoy/vant--mobile-mall#10]
你好，我觉得你项目效果很好，我想基于你的项目继续优化开发，但是没有看到开源协议，所以不知道你这里能不能完善一下开源协议，或者是否允许他人使用，谢谢。

**Comment by qianzhaoy** [comment]
已加. 😊

**Comment by linlinjava** [comment]
你好，现在做了开源小程序项目https://github.com/linlinjava/litemall， 现在准备基于你这个做移动版本，现在有一个相关的pr https://github.com/linlinjava/litemall/pull/157， 后面会不断优化。如果你感兴趣，非常欢迎交流一起完善。

**Comment by qianzhaoy** [comment]
ok. 先关注了
