### ISSUE TITLE
分类页面有点问题呢

### ISSUE THREAD

**Issue by dqiang** [qianzhaoy/vant--mobile-mall#4]
分类页面有点问题呢

**Comment by qianzhaoy** [comment]
能说下哪里有问题嘛
我这边是好的
![image](https://user-images.githubusercontent.com/14267409/49943957-2afe1400-ff24-11e8-8c21-719b4eb53ff1.png)

**Comment by dqiang** [comment]
如果左侧边栏数据多了，滚动是有问题的

**Comment by qianzhaoy** [comment]
ok, 我晚上回去测试一下. 😆

**Comment by qianzhaoy** [comment]
稍微改了一下  更新一下看看
