### ISSUE TITLE
请问路由中的asyncLoader方法是什么意思呢？

### ISSUE THREAD

**Issue by yangzhiganluk** [qianzhaoy/vant--mobile-mall#6]

**Comment by qianzhaoy** [comment]
一个高阶组件, 用作在路由里异步加载组件的, 作懒加载用的.

**Comment by qianzhaoy** [comment]
https://cn.vuejs.org/v2/guide/components-dynamic-async.html#%E5%A4%84%E7%90%86%E5%8A%A0%E8%BD%BD%E7%8A%B6%E6%80%81

主要想实现路由切换的时候的 loading 显示. 但是 vue 官网的 异步组件工厂函数 虽然说可以用在 vue-router 里. 但是实际上并不行. 就封装了这么一个高阶组件.

**Comment by qianzhaoy** [comment]
不过也有问题.  组件内的路由生命周期的钩子函数就无法使用了. 所以注释写了谨慎使用

**Comment by yangzhiganluk** [comment]
☺谢谢
