### ISSUE TITLE
user/order-entity-list中的component slot中 @handle="actionHandle($event, i)"是什么意思？

### ISSUE THREAD

**Issue by yangzhiganluk** [qianzhaoy/vant--mobile-mall#7]
actionHandle(handle, i) {
      this[handle] && this[handle](i);
    }
这是什么写法呢？

**Comment by qianzhaoy** [comment]
不同的按钮有不用的 handle 对应组件方法的名字.  所以直接判断一下 this[handle] 是否存在. 然后直接调用 this[handle]() 就行了.  handle 是一个字符串.
